# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8080

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ssm_cluster_db?useSSL=false&characterEncoding=utf8
        username: root
        password: 1234
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

logging:
  level:
    com.ssm.cluster.dao: debug

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

